name: Build Docker Image

on:
  workflow_call:
    outputs:
      image-name:
        description: "Name of the built Docker image"
        value: ${{ jobs.build-docker.outputs.image-name }}

jobs:
  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    outputs:
      image-name: bmstu_cpp_course-bmstu:latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        id: cache-docker-layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile', '**/docker-compose.yml') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/image/Dockerfile
          load: true
          tags: bmstu_cpp_course-bmstu:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Save Docker image as tarball
        run: docker save bmstu_cpp_course-bmstu:latest -o cpp_course_image.tar

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: cpp_course-image
          path: cpp_course_image.tar
          retention-days: 1

      # Move cache to avoid growing indefinitely
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
